// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"context"
	"crypto/tls"
	"fmt"
	"log"
	"math/big"
	"net/http"
	"time"

	errors "github.com/go-openapi/errors"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"
	graceful "github.com/tylerb/graceful"

	"github.com/Magicking/dao_tracabilite/internal"
	"github.com/Magicking/dao_tracabilite/restapi/operations"
)

// This file is safe to edit. Once it exists it will not be overwritten

//go:generate swagger generate server --target .. --name  --spec ../docs/dao_tracabilite.yml

var ethopts struct {
	WsURI        string `long:"ws-uri" env:"WS_URI" description:"Ethereum WS URI (e.g: ws://HOST:8546)"`
	Retry        int    `long:"retry" env:"RETRY" default:"3" description:"Max connection retry"`
	PrivateKey   string `long:"pkey" env:"PRIVATE_KEY" description:"hex encoded private key"`
	ContractAddr string `long:"addr" env:"ADDR_CONTRACT" description:"Contract Addr"`
}

var serviceopts struct {
	DbDSN string `long:"db-dsn" env:"DB_DSN" description:"Database DSN (e.g: /tmp/test.sqlite)"`
}

func configureFlags(api *operations.DAOTAPI) {
	ethOpts := swag.CommandLineOptionsGroup{
		LongDescription:  "",
		ShortDescription: "Ethereum options",
		Options:          &ethopts,
	}
	serviceOpts := swag.CommandLineOptionsGroup{
		LongDescription:  "",
		ShortDescription: "Service options",
		Options:          &serviceopts,
	}
	api.CommandLineOptionsGroups = []swag.CommandLineOptionsGroup{ethOpts, serviceOpts}
}

func configureAPI(api *operations.DAOTAPI) http.Handler {
	// configure the api here
	api.ServeError = errors.ServeError

	// Set your custom logger if needed. Default one is log.Printf
	// Expected interface func(string, ...interface{})
	//
	// Example:
	// api.Logger = log.Printf

	ctx := internal.InitContext(context.Background())
	//	internal.NewDBToContext(ctx, serviceopts.DbDSN)
	internal.NewCCToContext(ctx, ethopts.WsURI, ethopts.Retry)
	internal.Init(ctx, ethopts.ContractAddr, ethopts.PrivateKey)

	api.JSONConsumer = runtime.JSONConsumer()

	api.JSONProducer = runtime.JSONProducer()

	api.AssociationHandler = operations.AssociationHandlerFunc(func(params operations.AssociationParams) middleware.Responder {
		go func() {
			for _, id := range params.UIDS {
				t := time.Now()
				d := fmt.Sprintf("%d-%02d-%02dT%02d:%02d:%02d-00:00\n",
					t.Year(), t.Month(), t.Day(),
					t.Hour(), t.Minute(), t.Second())
				tx, err := internal.DAO.AddObjectToContainer(params.CID, id, "{\"info\":\"Scanned @ "+d+"\"}")
				if err != nil {
					log.Println("error: " + err.Error())
				}
				log.Println(tx)
				time.Sleep(2 * time.Second)
			}
		}()
		return operations.NewAssociationOK().WithPayload(true)
	})
	api.HistoriqueHandler = operations.HistoriqueHandlerFunc(func(params operations.HistoriqueParams) middleware.Responder {
		iID, err := internal.DAO.ToInternalId(params.Objetid)
		if err != nil {
			return middleware.NotImplemented("error: " + err.Error())
		}
		obj, err := internal.DAO.Objects(iID)
		if err != nil {
			return middleware.NotImplemented("error: " + err.Error())
		}
		var ret []string
		for i := int64(0); i < obj.TraceCount.Int64(); i++ {
			traceHash, err := internal.DAO.GetHistoryHash(params.Objetid, big.NewInt(i))
			if err != nil {
				return middleware.NotImplemented("error: " + err.Error())
			}
			trace, err := internal.DAO.Traces(traceHash)
			if err != nil {
				return middleware.NotImplemented("error: " + err.Error())
			}
			ret = append(ret, trace.Metadata)
		}
		return operations.NewHistoriqueOK().WithPayload(ret)
	})
	api.QrcodeHandler = operations.QrcodeHandlerFunc(func(params operations.QrcodeParams) middleware.Responder {
		return middleware.NotImplemented("operation .Qrcode has not yet been implemented")
	})

	api.ServerShutdown = func() {}

	return setupGlobalMiddleware(api.Serve(setupMiddlewares))
}

// The TLS configuration before HTTPS server starts.
func configureTLS(tlsConfig *tls.Config) {
	// Make all necessary changes to the TLS configuration here.
}

// As soon as server is initialized but not run yet, this function will be called.
// If you need to modify a config, store server instance to stop it individually later, this is the place.
// This function can be called multiple times, depending on the number of serving schemes.
// scheme value will be set accordingly: "http", "https" or "unix"
func configureServer(s *graceful.Server, scheme, addr string) {
}

// The middleware configuration is for the handler executors. These do not apply to the swagger.json document.
// The middleware executes after routing but before authentication, binding and validation
func setupMiddlewares(handler http.Handler) http.Handler {
	return handler
}

// The middleware configuration happens before anything, this middleware also applies to serving the swagger.json document.
// So this is a good place to plug in a panic handling middleware, logging and metrics
func setupGlobalMiddleware(handler http.Handler) http.Handler {
	return handler
}
