// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi DAOT
DAOT API



    Schemes:
      http
    Host: bmp.6120.eu
    BasePath: /api
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
