// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "swagger": "2.0",
  "info": {
    "description": "DAOT API\n",
    "title": "DAOT",
    "version": "0.1.0"
  },
  "host": "bmp.6120.eu",
  "basePath": "/api",
  "paths": {
    "/association/{c_id}": {
      "post": {
        "description": "Met des objets unitaire dans objets conteneurs",
        "summary": "Met des objets dans un objet",
        "operationId": "association",
        "parameters": [
          {
            "type": "string",
            "description": "Identifiant du conteneur",
            "name": "c_id",
            "in": "path",
            "required": true
          },
          {
            "description": "Identifiants des contenus",
            "name": "u_id_s",
            "in": "body",
            "required": true,
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Indique si lassociation s'est réalisé",
            "schema": {
              "type": "boolean"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/historique/{objetid}": {
      "get": {
        "description": "Retournes les informations d'historique",
        "summary": "Historiques metadata objet",
        "operationId": "historique",
        "parameters": [
          {
            "type": "string",
            "name": "objetid",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Liste ordonnée des interactions",
            "schema": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    },
    "/qrcode": {
      "post": {
        "description": "Créé un QRcode avec les metadata associés",
        "summary": "Créé un QRcode",
        "operationId": "qrcode",
        "responses": {
          "200": {
            "description": "QRcode identifiant interne",
            "schema": {
              "type": "string"
            }
          },
          "default": {
            "description": "Unexpected error",
            "schema": {
              "$ref": "#/definitions/Error"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Error": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "fields": {
          "type": "string"
        },
        "message": {
          "type": "string"
        }
      }
    }
  }
}`))
}
